### PR TITLE
use access policy for keyvault instead of rbac

### PR DESCRIPTION
**Pull request by william-liebenberg**
add system assigned identity to webapp
add kv access policy for webapp
reference existing kv secrets for webapp

### CODE REVIEW

**Comment by william-liebenberg** [comment]
@wicksipedia our SP doesn't have write permission for assigning roles. 

The KV references aren't validating after the last deployment.

Swapping this to access policies instead and enabled system assigned id to the webapp since it was disabled.

**Review by matt-goldman — APPROVED** [review]

**Comment by wicksipedia** [comment]
Maybe the standard around service principals setups should be updated. I prefer the RBAC method personally

**Review by wicksipedia — APPROVED** [review]
Let’s unblock this, we can always circle back and change it

**Comment by william-liebenberg** [comment]
Yes, I'd prefer rbac too - it's actually less work to do in the biceps :)

**Pull request merged**
